### ISSUE TITLE
Building libchimera.so

### ISSUE THREAD

**Issue by gliwka** [SocialIntelligence/Chimera4j#2]
How are you building chimera as a dynamic library?

**Comment by gliwka** [comment]
cc @SwiftEngineer

**Comment by SwiftEngineer** [comment]
@gliwka sorry for the insanely late reply. The company that I work for (who owns this repo) has moved to a new organization. This project was left behind and notifications I'd stopped getting notifications for it.

To answer your actual question (on the off chance it is still relevant): I used Docker to build the lib and threw a bunch of libs into it. It's a crazy mess and I still to this day can't believe it works, but seeing as how the lib from intel still to this day is nearly impossible to compile without heavily modifying it, I'll still regard it as a massive success lol.

Here's a link to the Docker image i used to build the dynamic lib https://github.com/SwiftEngineer/hyperscan/pull/1/files#diff-3254677a7917c6c01f55212f86c57fbfR61

**Comment by gliwka** [comment]
Thank you nevertheless.

Reading the chimera source code it seems to be only hyperscan with HS_FLAG_ALLOWEMPTY | HS_FLAG_PREFILTER | HS_FLAG_SOM_LEFTMOST flags set passing the matches through PCRE.

To ditch the licensing and build issues, we've decided to build a wrapper around hyperscan using Google's RE2J and hyperscan in prefilter mode, which emulates chimera perfectly.
